Q learning time reward
arpg-sophisticated/ar-tu-do pull request #110
Opened 2020-06-05 15:37 UTC by MaLangenk

2020-06-07 10:28 UTC, jhbruhn commented
Please fix the python formatting (and update the hook).

2020-06-11 08:57 UTC, ghost requested changes
Please format code correctly, then I'll approve directly

2020-06-13 10:35 UTC, marcelebbrecht commented
What about formatting ???

2020-06-18 09:25 UTC, MaLangenk commented
da stimmt noch was nicht mit dem formatiing!

2020-06-18 09:51 UTC, MaLangenk commented
got it :dagger:

2020-06-18 10:15 UTC, jhbruhn commented
zielgerade!

2020-06-19 08:55 UTC, marcelebbrecht commented
Da failen immer noch ein paar Format checks


Viele Grüße / Kind regards
Marcel Ebbrecht

GPG: http://gpg.fundm.one/029CAA8E.asc

MaLangenk <notifications@github.com> schrieb am Fr., 19. Juni 2020, 07:46:

> @MaLangenk <https://github.com/MaLangenk> requested your review on: #110
> <https://github.com/arpg-sophisticated/ar-tu-do/pull/110> Q learning time
> reward.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/arpg-sophisticated/ar-tu-do/pull/110#event-3461038310>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHFWFWMGH6WRFYVMNY5264LRXL3UZANCNFSM4NUAXOQQ>
> .
>

2020-06-19 09:07 UTC, marcelebbrecht commented
hab das jetzt mal eben gefixt. @MaLangenk:
Bitte führe mal 
 ./scripts/hooks/_install.sh
aus, dann installiert er die hooks.

Manuell kannst du mit 
 ./scripts/travis/check-format.sh
prüfen und mit 
 ./scripts/format/format-src.sh
formatieren. Aber wie gesagt, wenn die hooks drin sind, dann macht git das beim commit automatisch.

2020-06-19 09:10 UTC, ghost approved these changes

2020-06-19 13:39 UTC, MaLangenk commented
ah okay, danke. Ja das mit den hooks habe ich erst nicht gecheckt. Dass da jetzt noch zwei nicht formatiert waren, habe ich übersehen. Sorry und danke! :)

2020-06-21 21:29 UTC, Rothu approved these changes

2020-06-21 21:29 UTC, merged