Wallfollowing improvements
arpg-sophisticated/ar-tu-do pull request #118
Opened 2020-06-17 18:52 UTC by Rothu

Here the clustered walls from wall_detection are added to wallfollowing5.

2020-06-17 19:15 UTC, jhbruhn requested changes

2020-06-17 19:15 UTC, jhbruhn commented on ros_ws/src/autonomous/wallfollowing5/src/wallfollowing.cpp
>  void Wallfollowing::laserScanCallback(const sensor_msgs::LaserScan::ConstPtr& laserscan)
kann das nicht vielleicht raus?

2020-06-17 19:15 UTC, jhbruhn commented on ros_ws/src/autonomous/wallfollowing5/package.xml
> +  <build_depend>libpcl-all-dev</build_depend>
ìst das required? bin mir gerade selber nicht sicher, könnte aber vllt. erklären warum der travis build schluckauf hat?

2020-06-17 19:21 UTC, Rothu commented on ros_ws/src/autonomous/wallfollowing5/src/wallfollowing.cpp
>  void Wallfollowing::laserScanCallback(const sensor_msgs::LaserScan::ConstPtr& laserscan)
Das würd ich erst mal ganz gerne drin lassen als fallback

2020-06-17 21:15 UTC, Rothu commented on ros_ws/src/autonomous/wallfollowing5/package.xml
> +  <build_depend>libpcl-all-dev</build_depend>
Das hab ich entfernt

2020-06-18 10:14 UTC, jhbruhn approved these changes

2020-06-18 17:41 UTC, ghost approved these changes

2020-06-18 17:41 UTC, merged