Max speed info
arpg-sophisticated/ar-tu-do pull request #96
Opened 2020-05-25 00:58 UTC by Rothu

Hier eine Node, die unabhängig die für uns beste bekannte maximal mögliche Geschwindigkeit auf die topic /speed_info/max_speed schickt. Das könnte für die Analyse interessant sein.

2020-05-25 05:30 UTC, ghost approved these changes
afaik this only affects simulation, right?

2020-05-27 00:33 UTC, Rothu commented
Es funktioniert auch auf dem Auto, aber dazu fällt mir ein, dass das ganze mit den gazebo_state_telemtry-Daten in der Simulation genauer wär. Ich pass das Heute noch mal entsprechend an.

2020-05-31 13:54 UTC, jhbruhn requested changes
Sobald CircleFit in nem eigenen ROS Package ist kriegt das n approval :)

2020-05-31 16:55 UTC, marcelebbrecht commented
Es wäre aber schön, wenn das schon vorher ginge ... will damit arbeiten
;)
Am Sonntag, den 31.05.2020, 06:54 -0700 schrieb Jan-Henrik Bruhn:
> @jhbruhn requested changes on this pull request.
> 
> 
> Sobald CircleFit in nem eigenen ROS Package ist kriegt das n approval
> :)
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/arpg-sophisticated/ar-tu-do/pull/96#pullrequestreview-421497245
> ",
> "url": "
> https://github.com/arpg-sophisticated/ar-tu-do/pull/96#pullrequestreview-421497245
> ",
> "name": "View Pull Request"
> },
> "description": "View this Pull Request on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
-- 

Viele Grüße | Kind regards
Marcel Ebbrecht

GPG: http://gpg.fundm.one/029CAA8E.asc

2020-05-31 16:56 UTC, marcelebbrecht commented
und ich will nicht das git putschen ;)

Am Sonntag, den 31.05.2020, 06:54 -0700 schrieb Jan-Henrik Bruhn:
> @jhbruhn requested changes on this pull request.
> 
> Sobald CircleFit in nem eigenen ROS Package ist kriegt das n approval
> :)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 

Viele Grüße | Kind regards
Marcel Ebbrecht

GPG: http://gpg.fundm.one/029CAA8E.asc

2020-06-01 00:15 UTC, Rothu commented
> Sobald CircleFit in nem eigenen ROS Package ist kriegt das n approval :)

Ich habs angepasst.

2020-06-01 08:54 UTC, jhbruhn commented
Build failt nur weil irgendein https Zertifikat kaputt ist, sollte sieht aber gut aus.

2020-06-01 08:55 UTC, jhbruhn approved these changes

2020-06-01 08:55 UTC, merged